### ISSUE TITLE
Implementacion de una librería en una  aplicación de consola en C# 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo-kem#1]
[implementacion de una libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo-kem/files/14726315/implementacion.de.una.libreria.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica de evaluación tienen un porcentaje de 18 %

**Comment by josealfredo79** [comment]
@ErikCuevas03 Solamente es el diseño de la libreria...en la siguiente practica se implementa la libreria en el proyecto
